let wordList = [
  
    { word: "beetle", hint: "a type of insect" },
    { word: "octopus", hint: "a sea creature with eight arms" },
    { word: "volcano", hint: "a mountain that erupts with lava" },
    { word: "submarine", hint: "a vessel that operates underwater" },
    { word: "eclipse", hint: "when one celestial body obscures another" },
    { word: "drum", hint: "a percussion instrument" },
    { word: "whale", hint: "a large marine mammal" },
    { word: "robot", hint: "a machine capable of carrying out tasks" },
    { word: "pyramid", hint: "a geometric structure with a square base" },
    { word: "sunflower", hint: "a plant with large yellow flowers" },
    { word: "dinosaur", hint: "a prehistoric reptile" },
    { word: "carousel", hint: "a ride with rotating horses" },
    { word: "rainbow", hint: "a spectrum of colors in the sky" },
    { word: "accordion", hint: "a musical instrument with keys and bellows" },
    { word: "jigsaw", hint: "a type of puzzle with interlocking pieces" },
    { word: "glacier", hint: "a large mass of ice moving slowly" },
    { word: "mosaic", hint: "a pattern made of small colored pieces" },
    { word: "safari", hint: "an expedition to observe wildlife" },
    { word: "puzzle", hint: "a game requiring problem-solving" },
    { word: "telescope", hint: "an instrument for viewing distant objects" },
    { word: "sandwich", hint: "food consisting of fillings between slices of bread" },
    { word: "microphone", hint: "a device for amplifying sound" },
    { word: "sculpture", hint: "a three-dimensional piece of art" },
    { word: "monument", hint: "a structure built to commemorate a person or event" },
    { word: "snowflake", hint: "a crystal of frozen water" },
    { word: "carousel", hint: "a rotating amusement ride" },
    { word: "calculator", hint: "a device for performing arithmetic" },
    { word: "opera", hint: "a theatrical work set to music" },
    { word: "cactus", hint: "a plant with spines instead of leaves" },
    { word: "harp", hint: "a stringed musical instrument" },
    { word: "zeppelin", hint: "a type of airship" },
    { word: "jungle", hint: "a dense tropical forest" },
    { word: "fireworks", hint: "explosive devices for visual displays" },
    { word: "raindrop", hint: "a single drop of rain" },
    { word: "giraffe", hint: "a tall African animal with a long neck" },
    { word: "magnet", hint: "an object that attracts iron" },
    { word: "peninsula", hint: "a piece of land surrounded by water on three sides" },
    { word: "stadium", hint: "a large sports arena" },
    { word: "airplane", hint: "a vehicle for flying through the air" },
    { word: "diamond", hint: "a precious gemstone" },
    { word: "skeleton", hint: "the framework of bones in a body" },
    { word: "peacock", hint: "a bird known for its colorful feathers" },
    { word: "sandcastle", hint: "a sculpture made of sand" },
    { word: "lighthouse", hint: "a tower with a light to guide ships" },
    { word: "marathon", hint: "a long-distance running race" },
    { word: "volcano", hint: "a mountain with lava flow" },
    { word: "stethoscope", hint: "a device for listening to heartbeats" },
    { word: "puzzle", hint: "a game with pieces to solve" },
    { word: "chameleon", hint: "a lizard that changes color" },
    { word: "tornado", hint: "a rotating column of air" },
    { word: "castle", hint: "a large fortified building" },
    { word: "circus", hint: "a traveling show with animals and performers" },
    { word: "umbrella", hint: "a device for protection from rain" },
    { word: "rocket", hint: "a spacecraft for launching into space" },
    { word: "zeppelin", hint: "a type of airship" },
    { word: "violin", hint: "a stringed musical instrument" },
    { word: "photograph", hint: "a picture taken with a camera" },
    { word: "dolphin", hint: "a marine mammal known for intelligence" },
    { word: "kaleidoscope", hint: "a tube with changing patterns of colors" },
    { word: "typewriter", hint: "a machine for typing text" },
    { word: "harbor", hint: "a sheltered port for ships" },
    { word: "puzzle", hint: "a game that challenges problem-solving" },
    { word: "comet", hint: "a celestial body with a glowing tail" },
    { word: "beach", hint: "a sandy area by the sea" },
    { word: "skyscraper", hint: "a very tall building" },
    { word: "robot", hint: "a programmable machine" },
    { word: "trophy", hint: "an award for achievement" },
    { word: "fountain", hint: "a decorative water feature" },
    { word: "skateboard", hint: "a board mounted on wheels for skating" },
    { word: "zeppelin", hint: "a large airship" },
    { word: "carousel", hint: "a rotating amusement ride" },
    { word: "laptop", hint: "a portable computer" },
    { word: "waterfall", hint: "a flow of water over a cliff" },
    { word: "museum", hint: "a place to view art and artifacts" },
    { word: "horizon", hint: "the line where the earth meets the sky" },
    { word: "sunrise", hint: "the appearance of the sun in the morning" },
    { word: "moonlight", hint: "the light from the moon" },
    { word: "rainforest", hint: "a dense, tropical forest with high rainfall" },
    { word: "jewelry", hint: "decorative items worn on the body" },
    { word: "waterpark", hint: "a recreational area with water slides" },
    { word: "sunset", hint: "the setting of the sun in the evening" },
    { word: "cloud", hint: "a visible mass of water vapor in the sky" },
    { word: "keyboard", hint: "a device for typing" },
    { word: "ferry", hint: "a boat used to carry people across water" },
    { word: "zebra", hint: "an animal with black and white stripes" },
    { word: "telescope", hint: "an instrument for viewing distant objects" },
    { word: "canoe", hint: "a small boat paddled by hand" },
    { word: "orchid", hint: "a type of flowering plant" },
    { word: "crane", hint: "a tall machine used for lifting" },
    { word: "watermelon", hint: "a large fruit with green rind and red flesh" },
    { word: "sand", hint: "tiny grains found on beaches" },
    { word: "bicycle", hint: "a two-wheeled vehicle powered by pedaling" },



    { word: "algorithm", hint: "a set of rules for solving a problem" },
    { word: "API", hint: "Application Programming Interface" },
    { word: "binary", hint: "a base-2 numeral system" },
    { word: "cache", hint: "a storage layer that improves performance" },
    { word: "cloud", hint: "a model for delivering computing services over the internet" },
    { word: "data", hint: "information processed by a computer" },
    { word: "encryption", hint: "the process of converting data into a secure format" },
    { word: "framework", hint: "a structural support for building software" },
    { word: "gateway", hint: "a device that connects different networks" },
    { word: "HTML", hint: "HyperText Markup Language" },
    { word: "indexing", hint: "a technique for improving database query performance" },
    { word: "JavaScript", hint: "a scripting language for web development" },
    { word: "kernel", hint: "the core part of an operating system" },
    { word: "library", hint: "a collection of pre-written code" },
    { word: "microservice", hint: "an architectural style that structures an application as a collection of services" },
    { word: "network", hint: "a collection of computers connected to share resources" },
    { word: "object-oriented", hint: "a programming paradigm based on objects" },
    { word: "protocol", hint: "a set of rules for data communication" },
    { word: "query", hint: "a request for information from a database" },
    { word: "runtime", hint: "the period when a program is executing" },
    { word: "server", hint: "a computer system that provides resources or services" },
    { word: "string", hint: "a sequence of characters" },
    { word: "token", hint: "a unit of data used in authentication" },
    { word: "URL", hint: "Uniform Resource Locator" },
    { word: "version control", hint: "a system for managing changes to code" },
    { word: "websocket", hint: "a protocol for full-duplex communication over a single TCP connection" },
    { word: "XSS", hint: "Cross-Site Scripting, a security vulnerability" },
    { word: "YAML", hint: "a human-readable data serialization format" },
    { word: "zip", hint: "a file format for compression" },
    { word: "authentication", hint: "the process of verifying identity" },
    { word: "backend", hint: "the server-side part of a web application" },
    { word: "cache", hint: "temporary storage for improving speed" },
    { word: "debugging", hint: "the process of finding and fixing errors in code" },
    { word: "encryption", hint: "encoding data to protect it from unauthorized access" },
    { word: "firewall", hint: "a network security system that monitors and controls incoming and outgoing traffic" },
    { word: "Git", hint: "a version control system" },
    { word: "hashing", hint: "transforming data into a fixed-size string" },
    { word: "interface", hint: "a shared boundary between two systems" },
    { word: "JQuery", hint: "a JavaScript library for simplifying HTML document traversal" },
    { word: "kubernetes", hint: "an open-source platform for container orchestration" },
    { word: "load balancer", hint: "distributes network or application traffic across multiple servers" },
    { word: "middleware", hint: "software that connects different applications or services" },
    { word: "Node.js", hint: "a JavaScript runtime built on Chrome's V8 engine" },
    { word: "OAuth", hint: "an open standard for access delegation" },
    { word: "pipeline", hint: "a set of automated processes in software development" },
    { word: "query language", hint: "a language used to make queries to a database" },
    { word: "REST", hint: "Representational State Transfer, an architectural style for APIs" },
    { word: "SQL", hint: "Structured Query Language, used for managing databases" },
    { word: "TDD", hint: "Test-Driven Development" },
    { word: "UDP", hint: "User Datagram Protocol, a communication protocol" },
    { word: "virtual machine", hint: "an emulation of a computer system" },
    { word: "web API", hint: "an interface for web-based services" },
    { word: "XML", hint: "Extensible Markup Language, a markup language" },
    { word: "yield", hint: "a keyword in programming that returns a value" },
    { word: "zookeeper", hint: "a service for coordinating distributed applications" },
    { word: "agile", hint: "a methodology for iterative and incremental development" },
    { word: "binary tree", hint: "a data structure with nodes having at most two children" },
    { word: "containerization", hint: "the use of containers to package and deploy applications" },
    { word: "docker", hint: "a platform for containerizing applications" },
    { word: "encryption key", hint: "a secret used to encode and decode data" },
    { word: "fibonacci sequence", hint: "a sequence where each number is the sum of the two preceding ones" },
    { word: "git commit", hint: "a command to save changes to a local repository" },
    { word: "hash table", hint: "a data structure that maps keys to values" },
    { word: "iOS", hint: "Apple's mobile operating system" },
    { word: "JSON", hint: "JavaScript Object Notation, a data interchange format" },
    { word: "KPI", hint: "Key Performance Indicator, a measure of performance" },
    { word: "lambda", hint: "an anonymous function in programming" },
    { word: "microcontroller", hint: "a compact integrated circuit designed to govern a specific operation" },
    { word: "noSQL", hint: "a type of database that does not use SQL for querying" },
    { word: "OAuth2", hint: "an authorization framework" },
    { word: "public key", hint: "a cryptographic key used for encryption" },
    { word: "QR code", hint: "a type of matrix barcode" },
    { word: "RESTful API", hint: "an API adhering to REST principles" },
    { word: "static analysis", hint: "the examination of code without execution" },
    { word: "TCP", hint: "Transmission Control Protocol, a communication protocol" },
    { word: "unit test", hint: "a test of a single unit of code" },
    { word: "virtualization", hint: "the creation of virtual versions of physical resources" },
    { word: "web crawler", hint: "a program that scans the web for indexing" },
    { word: "XAML", hint: "Extensible Application Markup Language, used for UI definitions" },
    { word: "YARN", hint: "Yet Another Resource Negotiator, a resource management system" },
    { word: "zlib", hint: "a software library for data compression" },
    { word: "access control", hint: "the method of limiting access to resources" },
    { word: "back-end", hint: "server-side development" },
    { word: "CI/CD", hint: "Continuous Integration/Continuous Deployment" },
    { word: "domain name", hint: "a human-readable address for a website" },
    { word: "event-driven", hint: "a programming paradigm that responds to events" },
    { word: "Firebase", hint: "a platform for building web and mobile applications" },
    { word: "git branch", hint: "a parallel version of a repository" },
    { word: "hash function", hint: "a function that converts input into a fixed-size string" },
    { word: "intrusion detection", hint: "the process of monitoring network or system activities for malicious activities" },
    { word: "JIT", hint: "Just-In-Time compilation" },
    { word: "Kubernetes", hint: "an open-source platform for automating containerized application deployment" },
    { word: "logarithm", hint: "the inverse operation to exponentiation" },
    { word: "module", hint: "a self-contained unit of code" },
    { word: "namespace", hint: "a container for identifiers to avoid name conflicts" },
    { word: "OAuth2", hint: "an authorization framework" },
    { word: "postman", hint: "a tool for testing APIs" },
    { word: "query optimization", hint: "the process of improving database query performance" }
  ];